{"name": "test_4_cases_629", "status": "broken", "statusDetails": {"message": "NameError: name 'case_name' is not defined", "trace": "@pytest.mark.regress_tap\n    def test_4_cases_629():\n>       case_name('Отмена подписанного назначения лекарственного препарата')\nE       NameError: name 'case_name' is not defined\n\nautotest\\tests\\test_TAP.py:145: NameError"}, "start": 1714130332906, "stop": 1714130332906, "uuid": "bf76fe8c-117e-487b-9392-88dfba3884fc", "historyId": "8b63b73245cdab4d871aa19f21d3da39", "testCaseId": "8b63b73245cdab4d871aa19f21d3da39", "fullName": "autotest.tests.test_TAP#test_4_cases_629", "labels": [{"name": "tag", "value": "regress_tap"}, {"name": "parentSuite", "value": "autotest.tests"}, {"name": "suite", "value": "test_TAP"}, {"name": "host", "value": "Arutyun"}, {"name": "thread", "value": "19632-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "autotest.tests.test_TAP"}]}