{"name": "test_19_cases_601", "status": "broken", "statusDetails": {"message": "NameError: name 'case_name' is not defined", "trace": "@pytest.mark.regress_tap\n    def test_19_cases_601():\n>       case_name('Проверка обязательности поля \"Детализация\" при создании назначения лекарственного препарата')\nE       NameError: name 'case_name' is not defined\n\nautotest\\tests\\test_TAP.py:1398: NameError"}, "start": 1714130333782, "stop": 1714130333782, "uuid": "05c9ec0a-6eb4-4d66-ab3a-98900d78878d", "historyId": "00da2e9be02341b02d7235576af9cdfa", "testCaseId": "00da2e9be02341b02d7235576af9cdfa", "fullName": "autotest.tests.test_TAP#test_19_cases_601", "labels": [{"name": "tag", "value": "regress_tap"}, {"name": "parentSuite", "value": "autotest.tests"}, {"name": "suite", "value": "test_TAP"}, {"name": "host", "value": "Arutyun"}, {"name": "thread", "value": "19632-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "autotest.tests.test_TAP"}]}