{"name": "test_20_cases_605", "status": "broken", "statusDetails": {"message": "NameError: name 'case_name' is not defined", "trace": "@pytest.mark.regress_tap\n    def test_20_cases_605():\n>       case_name('Проверка обязательности поля \"Ед. измерения\" при создании назначения лекарственного препарата')\nE       NameError: name 'case_name' is not defined\n\nautotest\\tests\\test_TAP.py:1451: NameError"}, "start": 1714130333837, "stop": 1714130333837, "uuid": "a015f1f5-76a8-4e4e-b49b-436c68073f5f", "historyId": "c42711713dcc941892f8e6807d757632", "testCaseId": "c42711713dcc941892f8e6807d757632", "fullName": "autotest.tests.test_TAP#test_20_cases_605", "labels": [{"name": "tag", "value": "regress_tap"}, {"name": "parentSuite", "value": "autotest.tests"}, {"name": "suite", "value": "test_TAP"}, {"name": "host", "value": "Arutyun"}, {"name": "thread", "value": "19632-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "autotest.tests.test_TAP"}]}