{"name": "test_7_cases_677", "status": "broken", "statusDetails": {"message": "NameError: name 'case_name' is not defined", "trace": "@pytest.mark.regress_tap\n    def test_7_cases_677():\n>       case_name('Заполнение шапки назначения. Валидация поля \"Время\"')\nE       NameError: name 'case_name' is not defined\n\nautotest\\tests\\test_TAP.py:360: NameError"}, "start": 1714130333085, "stop": 1714130333086, "uuid": "baa17c5a-486c-4f5e-a69a-ef41572be7a9", "historyId": "2edc3b66a7856e132a2886695574d7a9", "testCaseId": "2edc3b66a7856e132a2886695574d7a9", "fullName": "autotest.tests.test_TAP#test_7_cases_677", "labels": [{"name": "tag", "value": "regress_tap"}, {"name": "parentSuite", "value": "autotest.tests"}, {"name": "suite", "value": "test_TAP"}, {"name": "host", "value": "Arutyun"}, {"name": "thread", "value": "19632-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "autotest.tests.test_TAP"}]}