{"name": "test_3_cases_597", "status": "broken", "statusDetails": {"message": "NameError: name 'case_name' is not defined", "trace": "@pytest.mark.regress_tap\n    def test_3_cases_597():\n>       case_name('Валидация полей \"Серия\" и \"Номер\" с флажком \"Бланк\" в форме рецепта')\nE       NameError: name 'case_name' is not defined\n\nautotest\\tests\\test_TAP.py:74: NameError"}, "start": 1714130332849, "stop": 1714130332849, "uuid": "91b2160a-6ac5-4c6b-a80d-ec2e8470fd5d", "historyId": "0abf8a297e7e4df2180032748d9a514a", "testCaseId": "0abf8a297e7e4df2180032748d9a514a", "fullName": "autotest.tests.test_TAP#test_3_cases_597", "labels": [{"name": "tag", "value": "regress_tap"}, {"name": "parentSuite", "value": "autotest.tests"}, {"name": "suite", "value": "test_TAP"}, {"name": "host", "value": "Arutyun"}, {"name": "thread", "value": "19632-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "autotest.tests.test_TAP"}]}