{"name": "test_11_case_611", "status": "broken", "statusDetails": {"message": "NameError: name 'case_name' is not defined", "trace": "@pytest.mark.regress_tap\n    def test_11_case_611():\n>       case_name('Валидация поля \"Детализация\" при создании назначения лекарственного препарата')\nE       NameError: name 'case_name' is not defined\n\nautotest\\tests\\test_TAP.py:677: NameError"}, "start": 1714130333319, "stop": 1714130333319, "uuid": "6c20022d-32db-4b51-9139-6d6ec6a5b967", "historyId": "886d229b5409e61b0897372505a86bd3", "testCaseId": "886d229b5409e61b0897372505a86bd3", "fullName": "autotest.tests.test_TAP#test_11_case_611", "labels": [{"name": "tag", "value": "regress_tap"}, {"name": "parentSuite", "value": "autotest.tests"}, {"name": "suite", "value": "test_TAP"}, {"name": "host", "value": "Arutyun"}, {"name": "thread", "value": "19632-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "autotest.tests.test_TAP"}]}