{"name": "test_22_cases_603", "status": "broken", "statusDetails": {"message": "NameError: name 'case_name' is not defined", "trace": "@pytest.mark.regress_tap\n    def test_22_cases_603():\n>       case_name('Проверка обязательности поля \"Кол-во на курс\" при создании назначения лекарственного препарата')\nE       NameError: name 'case_name' is not defined\n\nautotest\\tests\\test_TAP.py:1549: NameError"}, "start": 1714130333951, "stop": 1714130333951, "uuid": "44ea52df-f9c0-4152-8fbc-7d417b1d1c5d", "historyId": "77b5b3b674be581840e3933696ffc08c", "testCaseId": "77b5b3b674be581840e3933696ffc08c", "fullName": "autotest.tests.test_TAP#test_22_cases_603", "labels": [{"name": "tag", "value": "regress_tap"}, {"name": "parentSuite", "value": "autotest.tests"}, {"name": "suite", "value": "test_TAP"}, {"name": "host", "value": "Arutyun"}, {"name": "thread", "value": "19632-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "autotest.tests.test_TAP"}]}