{"name": "test_21_cases_604", "status": "broken", "statusDetails": {"message": "NameError: name 'case_name' is not defined", "trace": "@pytest.mark.regress_tap\n    def test_21_cases_604():\n>       case_name('Проверка обязательности поля \"Кол-во дней\" при создании назначения лекарственного препарата')\nE       NameError: name 'case_name' is not defined\n\nautotest\\tests\\test_TAP.py:1504: NameError"}, "start": 1714130333894, "stop": 1714130333894, "uuid": "3551634c-e627-4947-a163-4200beffcefb", "historyId": "ea79f7935f71e6cd7b2e647c84b51c18", "testCaseId": "ea79f7935f71e6cd7b2e647c84b51c18", "fullName": "autotest.tests.test_TAP#test_21_cases_604", "labels": [{"name": "tag", "value": "regress_tap"}, {"name": "parentSuite", "value": "autotest.tests"}, {"name": "suite", "value": "test_TAP"}, {"name": "host", "value": "Arutyun"}, {"name": "thread", "value": "19632-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "autotest.tests.test_TAP"}]}