{"name": "test_26_cases_631", "status": "broken", "statusDetails": {"message": "NameError: name 'case_name' is not defined", "trace": "@pytest.mark.regress_tap\n    def test_26_cases_631():\n>       case_name('Проверка возможности редактирования назначения лекарственного препарата в статусе \"Подписано\"')\nE       NameError: name 'case_name' is not defined\n\nautotest\\tests\\test_TAP.py:1843: NameError"}, "start": 1714130334182, "stop": 1714130334182, "uuid": "6bec32c2-132f-4282-afdb-2cf6e6a27e25", "historyId": "7c4a38f2c12e05433fc01681cbd3d91c", "testCaseId": "7c4a38f2c12e05433fc01681cbd3d91c", "fullName": "autotest.tests.test_TAP#test_26_cases_631", "labels": [{"name": "tag", "value": "regress_tap"}, {"name": "parentSuite", "value": "autotest.tests"}, {"name": "suite", "value": "test_TAP"}, {"name": "host", "value": "Arutyun"}, {"name": "thread", "value": "19632-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "autotest.tests.test_TAP"}]}