{"name": "test_8_cases_649", "status": "broken", "statusDetails": {"message": "NameError: name 'case_name' is not defined", "trace": "@pytest.mark.regress_tap\n    def test_8_cases_649():\n>       case_name('Подписание назначения лекарственного препарата из создания назначения')\nE       NameError: name 'case_name' is not defined\n\nautotest\\tests\\test_TAP.py:432: NameError"}, "start": 1714130333146, "stop": 1714130333146, "uuid": "cbf5d77a-2958-4c6b-aab3-380f280222df", "historyId": "f999e553ad47314b28a0b555c4664178", "testCaseId": "f999e553ad47314b28a0b555c4664178", "fullName": "autotest.tests.test_TAP#test_8_cases_649", "labels": [{"name": "tag", "value": "regress_tap"}, {"name": "parentSuite", "value": "autotest.tests"}, {"name": "suite", "value": "test_TAP"}, {"name": "host", "value": "Arutyun"}, {"name": "thread", "value": "19632-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "autotest.tests.test_TAP"}]}