{"name": "test_23_cases_602", "status": "broken", "statusDetails": {"message": "NameError: name 'case_name' is not defined", "trace": "@pytest.mark.regress_tap\n    def test_23_cases_602():\n>       case_name('Проверка обязательности поля \"Путь введения\" при создании назначения лекарственного препарата')\nE       NameError: name 'case_name' is not defined\n\nautotest\\tests\\test_TAP.py:1602: NameError"}, "start": 1714130334010, "stop": 1714130334011, "uuid": "3181c1f8-8f8f-4ff9-93ca-621058974439", "historyId": "8e5b163aaea3beb6747f9e699a5c9037", "testCaseId": "8e5b163aaea3beb6747f9e699a5c9037", "fullName": "autotest.tests.test_TAP#test_23_cases_602", "labels": [{"name": "tag", "value": "regress_tap"}, {"name": "parentSuite", "value": "autotest.tests"}, {"name": "suite", "value": "test_TAP"}, {"name": "host", "value": "Arutyun"}, {"name": "thread", "value": "19632-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "autotest.tests.test_TAP"}]}