{"name": "test_31_cases_636", "status": "broken", "statusDetails": {"message": "NameError: name 'case_name' is not defined", "trace": "@pytest.mark.regress_tap\n    def test_31_cases_636():\n>       case_name('Проверка поля \"Льгота\" при выписке рецепта для пациента с одной льготой')\nE       NameError: name 'case_name' is not defined\n\nautotest\\tests\\test_TAP.py:2132: NameError"}, "start": 1714130336090, "stop": 1714130336090, "uuid": "3a830113-6379-44ee-b26d-b1a9cde84117", "historyId": "9f013db4ebd7ff8a905e0698878c6585", "testCaseId": "9f013db4ebd7ff8a905e0698878c6585", "fullName": "autotest.tests.test_TAP#test_31_cases_636", "labels": [{"name": "tag", "value": "regress_tap"}, {"name": "parentSuite", "value": "autotest.tests"}, {"name": "suite", "value": "test_TAP"}, {"name": "host", "value": "Arutyun"}, {"name": "thread", "value": "19632-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "autotest.tests.test_TAP"}]}