{"name": "test_27_cases_600", "status": "broken", "statusDetails": {"message": "NameError: name 'case_name' is not defined", "trace": "@pytest.mark.regress_tap\n    def test_27_cases_600():\n>       case_name('Проверка обязательности поля \"Врач\" при создании назначения лекарственного препарата')\nE       NameError: name 'case_name' is not defined\n\nautotest\\tests\\test_TAP.py:1863: NameError"}, "start": 1714130334236, "stop": 1714130334237, "uuid": "1a0a44cc-d931-498e-abfa-ba2c5a13c16e", "historyId": "0cbd0654b6652da37db2be3528c6cad5", "testCaseId": "0cbd0654b6652da37db2be3528c6cad5", "fullName": "autotest.tests.test_TAP#test_27_cases_600", "labels": [{"name": "tag", "value": "regress_tap"}, {"name": "parentSuite", "value": "autotest.tests"}, {"name": "suite", "value": "test_TAP"}, {"name": "host", "value": "Arutyun"}, {"name": "thread", "value": "19632-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "autotest.tests.test_TAP"}]}